/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityIndexRouteImport } from './routes/activity/index'
import { Route as AddressIndexRouteImport } from './routes/address/index'
import { Route as FacilityChar123FacilityChar125RouteImport } from './routes/facility/{-$facility}'
import { Route as InquiryIndexRouteImport } from './routes/inquiry/index'
import { Route as LoginChar123BaseChar125RouteImport } from './routes/login/{-$base}'
import { Route as MasterIndexRouteImport } from './routes/master/index'
import { Route as PatientIndexRouteImport } from './routes/patient/index'
import { Route as ProcessChar123PatientIdChar125RouteImport } from './routes/process/{-$patientId}'
import { Route as ReportIndexRouteImport } from './routes/report/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StatisticsChar123IdChar125RouteImport } from './routes/statistics/{-$id}'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as WebappIndexRouteImport } from './routes/webapp/index'
import { Route as AnswerBaseAppIdRouteImport } from './routes/answer/$base.$appId'
import { Route as AnswerPatientChar123IdChar125RouteImport } from './routes/answer/patient.{-$id}'
import { Route as AppointmentChar123PatientIdChar125Char123AppIdChar125RouteImport } from './routes/appointment/{-$patientId}.{-$appId}'
import { Route as ReferraltoChar123PatientIdChar125Char123RefIdChar125RouteImport } from './routes/referralto/{-$patientId}.{-$refId}'
import { Route as ReplyChar123PatientIdChar125Char123RepIdChar125RouteImport } from './routes/reply/{-$patientId}.{-$repId}'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressIndexRoute = AddressIndexRouteImport.update({
  id: '/address/',
  path: '/address/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityChar123FacilityChar125Route =
  FacilityChar123FacilityChar125RouteImport.update({
    id: '/facility/{-$facility}',
    path: '/facility/{-$facility}',
    getParentRoute: () => rootRouteImport,
  } as any)
const InquiryIndexRoute = InquiryIndexRouteImport.update({
  id: '/inquiry/',
  path: '/inquiry/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginChar123BaseChar125Route = LoginChar123BaseChar125RouteImport.update({
  id: '/login/{-$base}',
  path: '/login/{-$base}',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterIndexRoute = MasterIndexRouteImport.update({
  id: '/master/',
  path: '/master/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessChar123PatientIdChar125Route =
  ProcessChar123PatientIdChar125RouteImport.update({
    id: '/process/{-$patientId}',
    path: '/process/{-$patientId}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportIndexRoute = ReportIndexRouteImport.update({
  id: '/report/',
  path: '/report/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsChar123IdChar125Route =
  StatisticsChar123IdChar125RouteImport.update({
    id: '/statistics/{-$id}',
    path: '/statistics/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebappIndexRoute = WebappIndexRouteImport.update({
  id: '/webapp/',
  path: '/webapp/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerBaseAppIdRoute = AnswerBaseAppIdRouteImport.update({
  id: '/answer/$base/$appId',
  path: '/answer/$base/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerPatientChar123IdChar125Route =
  AnswerPatientChar123IdChar125RouteImport.update({
    id: '/answer/patient/{-$id}',
    path: '/answer/patient/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppointmentChar123PatientIdChar125Char123AppIdChar125Route =
  AppointmentChar123PatientIdChar125Char123AppIdChar125RouteImport.update({
    id: '/appointment/{-$patientId}/{-$appId}',
    path: '/appointment/{-$patientId}/{-$appId}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReferraltoChar123PatientIdChar125Char123RefIdChar125Route =
  ReferraltoChar123PatientIdChar125Char123RefIdChar125RouteImport.update({
    id: '/referralto/{-$patientId}/{-$refId}',
    path: '/referralto/{-$patientId}/{-$refId}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReplyChar123PatientIdChar125Char123RepIdChar125Route =
  ReplyChar123PatientIdChar125Char123RepIdChar125RouteImport.update({
    id: '/reply/{-$patientId}/{-$repId}',
    path: '/reply/{-$patientId}/{-$repId}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/facility/{-$facility}': typeof FacilityChar123FacilityChar125Route
  '/login/{-$base}': typeof LoginChar123BaseChar125Route
  '/process/{-$patientId}': typeof ProcessChar123PatientIdChar125Route
  '/statistics/{-$id}': typeof StatisticsChar123IdChar125Route
  '/activity/': typeof ActivityIndexRoute
  '/address/': typeof AddressIndexRoute
  '/inquiry/': typeof InquiryIndexRoute
  '/master/': typeof MasterIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/report/': typeof ReportIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/user/': typeof UserIndexRoute
  '/webapp/': typeof WebappIndexRoute
  '/answer/$base/$appId': typeof AnswerBaseAppIdRoute
  '/answer/patient/{-$id}': typeof AnswerPatientChar123IdChar125Route
  '/appointment/{-$patientId}/{-$appId}': typeof AppointmentChar123PatientIdChar125Char123AppIdChar125Route
  '/referralto/{-$patientId}/{-$refId}': typeof ReferraltoChar123PatientIdChar125Char123RefIdChar125Route
  '/reply/{-$patientId}/{-$repId}': typeof ReplyChar123PatientIdChar125Char123RepIdChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/facility/{-$facility}': typeof FacilityChar123FacilityChar125Route
  '/login/{-$base}': typeof LoginChar123BaseChar125Route
  '/process/{-$patientId}': typeof ProcessChar123PatientIdChar125Route
  '/statistics/{-$id}': typeof StatisticsChar123IdChar125Route
  '/activity': typeof ActivityIndexRoute
  '/address': typeof AddressIndexRoute
  '/inquiry': typeof InquiryIndexRoute
  '/master': typeof MasterIndexRoute
  '/patient': typeof PatientIndexRoute
  '/report': typeof ReportIndexRoute
  '/staff': typeof StaffIndexRoute
  '/user': typeof UserIndexRoute
  '/webapp': typeof WebappIndexRoute
  '/answer/$base/$appId': typeof AnswerBaseAppIdRoute
  '/answer/patient/{-$id}': typeof AnswerPatientChar123IdChar125Route
  '/appointment/{-$patientId}/{-$appId}': typeof AppointmentChar123PatientIdChar125Char123AppIdChar125Route
  '/referralto/{-$patientId}/{-$refId}': typeof ReferraltoChar123PatientIdChar125Char123RefIdChar125Route
  '/reply/{-$patientId}/{-$repId}': typeof ReplyChar123PatientIdChar125Char123RepIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/facility/{-$facility}': typeof FacilityChar123FacilityChar125Route
  '/login/{-$base}': typeof LoginChar123BaseChar125Route
  '/process/{-$patientId}': typeof ProcessChar123PatientIdChar125Route
  '/statistics/{-$id}': typeof StatisticsChar123IdChar125Route
  '/activity/': typeof ActivityIndexRoute
  '/address/': typeof AddressIndexRoute
  '/inquiry/': typeof InquiryIndexRoute
  '/master/': typeof MasterIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/report/': typeof ReportIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/user/': typeof UserIndexRoute
  '/webapp/': typeof WebappIndexRoute
  '/answer/$base/$appId': typeof AnswerBaseAppIdRoute
  '/answer/patient/{-$id}': typeof AnswerPatientChar123IdChar125Route
  '/appointment/{-$patientId}/{-$appId}': typeof AppointmentChar123PatientIdChar125Char123AppIdChar125Route
  '/referralto/{-$patientId}/{-$refId}': typeof ReferraltoChar123PatientIdChar125Char123RefIdChar125Route
  '/reply/{-$patientId}/{-$repId}': typeof ReplyChar123PatientIdChar125Char123RepIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/facility/{-$facility}'
    | '/login/{-$base}'
    | '/process/{-$patientId}'
    | '/statistics/{-$id}'
    | '/activity/'
    | '/address/'
    | '/inquiry/'
    | '/master/'
    | '/patient/'
    | '/report/'
    | '/staff/'
    | '/user/'
    | '/webapp/'
    | '/answer/$base/$appId'
    | '/answer/patient/{-$id}'
    | '/appointment/{-$patientId}/{-$appId}'
    | '/referralto/{-$patientId}/{-$refId}'
    | '/reply/{-$patientId}/{-$repId}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/facility/{-$facility}'
    | '/login/{-$base}'
    | '/process/{-$patientId}'
    | '/statistics/{-$id}'
    | '/activity'
    | '/address'
    | '/inquiry'
    | '/master'
    | '/patient'
    | '/report'
    | '/staff'
    | '/user'
    | '/webapp'
    | '/answer/$base/$appId'
    | '/answer/patient/{-$id}'
    | '/appointment/{-$patientId}/{-$appId}'
    | '/referralto/{-$patientId}/{-$refId}'
    | '/reply/{-$patientId}/{-$repId}'
  id:
    | '__root__'
    | '/'
    | '/facility/{-$facility}'
    | '/login/{-$base}'
    | '/process/{-$patientId}'
    | '/statistics/{-$id}'
    | '/activity/'
    | '/address/'
    | '/inquiry/'
    | '/master/'
    | '/patient/'
    | '/report/'
    | '/staff/'
    | '/user/'
    | '/webapp/'
    | '/answer/$base/$appId'
    | '/answer/patient/{-$id}'
    | '/appointment/{-$patientId}/{-$appId}'
    | '/referralto/{-$patientId}/{-$refId}'
    | '/reply/{-$patientId}/{-$repId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FacilityChar123FacilityChar125Route: typeof FacilityChar123FacilityChar125Route
  LoginChar123BaseChar125Route: typeof LoginChar123BaseChar125Route
  ProcessChar123PatientIdChar125Route: typeof ProcessChar123PatientIdChar125Route
  StatisticsChar123IdChar125Route: typeof StatisticsChar123IdChar125Route
  ActivityIndexRoute: typeof ActivityIndexRoute
  AddressIndexRoute: typeof AddressIndexRoute
  InquiryIndexRoute: typeof InquiryIndexRoute
  MasterIndexRoute: typeof MasterIndexRoute
  PatientIndexRoute: typeof PatientIndexRoute
  ReportIndexRoute: typeof ReportIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  UserIndexRoute: typeof UserIndexRoute
  WebappIndexRoute: typeof WebappIndexRoute
  AnswerBaseAppIdRoute: typeof AnswerBaseAppIdRoute
  AnswerPatientChar123IdChar125Route: typeof AnswerPatientChar123IdChar125Route
  AppointmentChar123PatientIdChar125Char123AppIdChar125Route: typeof AppointmentChar123PatientIdChar125Char123AppIdChar125Route
  ReferraltoChar123PatientIdChar125Char123RefIdChar125Route: typeof ReferraltoChar123PatientIdChar125Char123RefIdChar125Route
  ReplyChar123PatientIdChar125Char123RepIdChar125Route: typeof ReplyChar123PatientIdChar125Char123RepIdChar125Route
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/': {
      id: '/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address/': {
      id: '/address/'
      path: '/address'
      fullPath: '/address/'
      preLoaderRoute: typeof AddressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility/{-$facility}': {
      id: '/facility/{-$facility}'
      path: '/facility/{-$facility}'
      fullPath: '/facility/{-$facility}'
      preLoaderRoute: typeof FacilityChar123FacilityChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry/': {
      id: '/inquiry/'
      path: '/inquiry'
      fullPath: '/inquiry/'
      preLoaderRoute: typeof InquiryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/{-$base}': {
      id: '/login/{-$base}'
      path: '/login/{-$base}'
      fullPath: '/login/{-$base}'
      preLoaderRoute: typeof LoginChar123BaseChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/': {
      id: '/master/'
      path: '/master'
      fullPath: '/master/'
      preLoaderRoute: typeof MasterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/patient'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process/{-$patientId}': {
      id: '/process/{-$patientId}'
      path: '/process/{-$patientId}'
      fullPath: '/process/{-$patientId}'
      preLoaderRoute: typeof ProcessChar123PatientIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/': {
      id: '/report/'
      path: '/report'
      fullPath: '/report/'
      preLoaderRoute: typeof ReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics/{-$id}': {
      id: '/statistics/{-$id}'
      path: '/statistics/{-$id}'
      fullPath: '/statistics/{-$id}'
      preLoaderRoute: typeof StatisticsChar123IdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webapp/': {
      id: '/webapp/'
      path: '/webapp'
      fullPath: '/webapp/'
      preLoaderRoute: typeof WebappIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer/$base/$appId': {
      id: '/answer/$base/$appId'
      path: '/answer/$base/$appId'
      fullPath: '/answer/$base/$appId'
      preLoaderRoute: typeof AnswerBaseAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer/patient/{-$id}': {
      id: '/answer/patient/{-$id}'
      path: '/answer/patient/{-$id}'
      fullPath: '/answer/patient/{-$id}'
      preLoaderRoute: typeof AnswerPatientChar123IdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment/{-$patientId}/{-$appId}': {
      id: '/appointment/{-$patientId}/{-$appId}'
      path: '/appointment/{-$patientId}/{-$appId}'
      fullPath: '/appointment/{-$patientId}/{-$appId}'
      preLoaderRoute: typeof AppointmentChar123PatientIdChar125Char123AppIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referralto/{-$patientId}/{-$refId}': {
      id: '/referralto/{-$patientId}/{-$refId}'
      path: '/referralto/{-$patientId}/{-$refId}'
      fullPath: '/referralto/{-$patientId}/{-$refId}'
      preLoaderRoute: typeof ReferraltoChar123PatientIdChar125Char123RefIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reply/{-$patientId}/{-$repId}': {
      id: '/reply/{-$patientId}/{-$repId}'
      path: '/reply/{-$patientId}/{-$repId}'
      fullPath: '/reply/{-$patientId}/{-$repId}'
      preLoaderRoute: typeof ReplyChar123PatientIdChar125Char123RepIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FacilityChar123FacilityChar125Route: FacilityChar123FacilityChar125Route,
  LoginChar123BaseChar125Route: LoginChar123BaseChar125Route,
  ProcessChar123PatientIdChar125Route: ProcessChar123PatientIdChar125Route,
  StatisticsChar123IdChar125Route: StatisticsChar123IdChar125Route,
  ActivityIndexRoute: ActivityIndexRoute,
  AddressIndexRoute: AddressIndexRoute,
  InquiryIndexRoute: InquiryIndexRoute,
  MasterIndexRoute: MasterIndexRoute,
  PatientIndexRoute: PatientIndexRoute,
  ReportIndexRoute: ReportIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  UserIndexRoute: UserIndexRoute,
  WebappIndexRoute: WebappIndexRoute,
  AnswerBaseAppIdRoute: AnswerBaseAppIdRoute,
  AnswerPatientChar123IdChar125Route: AnswerPatientChar123IdChar125Route,
  AppointmentChar123PatientIdChar125Char123AppIdChar125Route:
    AppointmentChar123PatientIdChar125Char123AppIdChar125Route,
  ReferraltoChar123PatientIdChar125Char123RefIdChar125Route:
    ReferraltoChar123PatientIdChar125Char123RefIdChar125Route,
  ReplyChar123PatientIdChar125Char123RepIdChar125Route:
    ReplyChar123PatientIdChar125Char123RepIdChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
